### ISSUE TITLE
[Duvida] Como executar

### ISSUE THREAD

**Issue by kakamorsch** [kavitormorsch/Site-de-Testes#1]
Olá!
Eu esbarrei no seu projeto e gostaria de saber como faço pra executar na minha máquina. 
Existe alguma documentação? Como posso contribuir?

**Comment by kavitormorsch** [comment]
Olá, atualizei o arquivo README do projeto com instruções para executar o projeto. Caso queira fazer uma contribuição, pode dar sugestões por aqui mesmo com as labels adequadas. Por enquanto a única documentação do projeto é o README.

**Comment by kakamorsch** [comment]
Tenho deficiência visual e não consigo ver a imagem. 
Poderia escrever as etapas de forma mais clara?
Preciso instalar alguma coisa para executar o projeto?

**Comment by kavitormorsch** [comment]
Atualizei o arquivo README com as etapas descritas mais claramente e com o que precisa para poder executar o projeto.
